"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const sutoring = require("../../dist/index");
//const text = "aba";
const text = "abaababaabaababaababaabaababaaba";
//const text = "abaababaabaababaababaabaababaabaababaababaabaababaababaabaababaabaababaababaabaababaabaababaababaaba";
const tree = sutoring.Trees.BlockTree.makeBlockTree(text);
const logicTree = sutoring.Trees.BlockTree.convert(tree);
//logicTree.graphOption.drawingFunction = undefined;
sutoring.Console.graph(logicTree);
